### ISSUE TITLE
Set Agent version more explicitly

### ISSUE THREAD

**Issue by astj** [nonylene/MackerelAgentAndroid#7]
Currently, MackerelAgentAndroid (in Play Store) reports its `agent-version` as `1.0` in host metadata.
Normally this `agent-version` points [official mackerel-agent](https://github.com/mackerelio/mackerel-agent)'s version and the value `1.0` may be confusing, especially when official agent bumps its version to 1.0.

So, is it possible to set some prefix to `agent-version` (like "MackerelAgentAndroid 1.0" or something)?

Thanks.

**Comment by nonylene** [comment]
I will set `"MackerelAgentAndroid "` prefix in next version, Thanks!
